lib/qiita/markdown/filters/sanitize.rb, spec/qiita/markdown/processor_spec.rb
Hi.
This change is to support text-align on table header.
=> Modify support text-align syntax on table

lib/qiita/markdown/filters/sanitize.rb, lib/qiita/markdown/processor.rb, spec/qiita/markdown/processor_spec.rb
Because there might be posibility of malicious script in given string.
=> Sanitization should be done at the last phase

.rubocop_todo.yml, lib/qiita/markdown/filters/mention.rb, spec/qiita/markdown/processor_spec.rb
This results in sending mentions to all allowed users.
=> Support `@all`

lib/qiita/markdown/filters/mention.rb, spec/qiita/markdown/processor_spec.rb
so that we can mention users whose names are 2 characters (exists from time immemorial...)
=> Relax mention name patterns with 2 characters length

lib/qiita/markdown/filters/sanitize.rb
Please allow video element. I need embed screen casts.
=> Allow video element

.travis.yml
See https://github.com/bundler/bundler/issues/3558
=> Update bundler to fix bundler version on travis-ci

lib/qiita/markdown/filters/syntax_highlight.rb
Let SyntaxHighlightFilter stop if it takes longer than `context[:syntax_highlight_timeout]` seconds.
Note that it is "soft" timeout, rather than "hard" timeout such as one provided by `Timeout::timeout`, so a filter may not stop immediately after it passes the time limit.
If anyone is curious about why we don't just use `Timeout::timeout`, here's the reason [Why Ruby’s Timeout is dangerous (and Thread.raise is terrifying) - Julia Evans](https://jvns.ca/blog/2015/11/27/why-rubys-timeout-is-dangerous-and-thread-dot-raise-is-terrifying/)
Related to https://github.com/increments/Qiita/issues/10753 (summary: Qiita's edit request renderer may fail if the request contains too many code blocks)
=> Add timeout support to syntax highlight filter

.rubocop.yml, .travis.yml, Rakefile, benchmark/heading_anchor_rendering.rb, lib/qiita/markdown/filters/group_mention.rb, lib/qiita/markdown/filters/sanitize.rb, lib/qiita/markdown/filters/simplify.rb, qiita-markdown.gemspec
=> Update Rubocop and test ruby versions

CHANGELOG.md, lib/qiita/markdown/filters/code.rb, qiita-markdown.gemspec, spec/qiita/markdown/summary_processor_spec.rb
Follow-up to https://github.com/increments/greenmat/pull/5.
=> Follow change of code block metadata attribute in greenmat

lib/qiita/markdown/filters/user_input_sanitizer.rb, spec/qiita/markdown/processor_spec.rb
Follow-up to https://github.com/increments/qiita-markdown/pull/46.
=> Add missing sanitization for <div> class attribute

CHANGELOG.md, lib/qiita/markdown/filters/user_input_sanitizer.rb, spec/qiita/markdown/processor_spec.rb
=> Fix to sanitize <input> which was unexpectedly permitted

lib/qiita/markdown/embed/code_pen.rb, lib/qiita/markdown/embed/tweet.rb, lib/qiita/markdown/filters/final_sanitizer.rb, lib/qiita/markdown/filters/user_input_sanitizer.rb, lib/qiita/markdown/transformers/filter_attributes.rb, spec/qiita/markdown/processor_spec.rb
Although we only allowed minimal data attributes in embedded code, we increased the number of data attributes that we allow
=> Allow data attributes used in embed code

lib/qiita/markdown/embed/code_pen.rb, lib/qiita/markdown/transformers/filter_script.rb, spec/qiita/markdown/processor_spec.rb
Script src domain has changed from https://public-assets.codepen.io/assets/embed/ei.js to https://static.codepen.io/assets/embed/ei.js
=> Accept static.codepen.io as codepen script url

qiita-markdown.gemspec
https://github.com/increments/greenmat/pull/6
=> Use greenmat 3.2.2.4

CHANGELOG.md, lib/qiita/markdown/version.rb
- https://github.com/increments/qiita-markdown/pull/72
=> Update to v0.28.0

CHANGELOG.md, qiita-markdown.gemspec, spec/qiita/markdown/processor_spec.rb
https://github.com/increments/greenmat/pull/8
- footnote description syntax can be included in code block.
=> Use greenmat 3.5.1.0

CHANGELOG.md, qiita-markdown.gemspec, spec/qiita/markdown/processor_spec.rb
https://github.com/increments/greenmat/pull/10
- Skip parsing `<details>` and `<summary>` tag
=> Use greenmat 3.5.1.1

lib/qiita/markdown/transformers/filter_iframe.rb, lib/qiita/markdown/transformers/filter_script.rb, spec/qiita/markdown/processor_spec.rb
Update to iframe transformaer to fix iframe width
=> Update iframe transformer to fix iframe width

lib/qiita/markdown/filters/custom_block.rb
- Fixed problem that `ALLOWED_TYPES` expects an array, but it was a string.
=> Fix allowed types

lib/qiita/markdown/filters/custom_block.rb, spec/qiita/markdown/processor_spec.rb
- Change messsage notation to note notation
```diff
-:::message 
+:::note
:::
```
=> Rename message notation to note notation

CHANGELOG.md, qiita-markdown.gemspec
- Bump greenmat from 3.5.1.2 to 3.5.1.3
- https://github.com/increments/greenmat/pull/16
=> Bump greenmat from 3.5.1.2 to 3.5.1.3

CHANGELOG.md, qiita-markdown.gemspec
- Bump greenmat from 3.5.1.3 to 3.5.1.4
- https://github.com/increments/greenmat/pull/19
=> Bump greenmat from 3.5.1.3 to 3.5.1.4

CHANGELOG.md, lib/qiita/markdown/version.rb
- https://github.com/increments/qiita-markdown/pull/123
- https://github.com/increments/qiita-markdown/pull/122
=> Release v0.43.0

CHANGELOG.md, lib/qiita/markdown/version.rb
- https://github.com/increments/qiita-markdown/pull/125
- https://github.com/increments/qiita-markdown/pull/126
=> Release v0.44.0

CHANGELOG.md, lib/qiita/markdown/version.rb
release
- https://github.com/increments/qiita-markdown/pull/137
=> Release v1.0.1

CHANGELOG.md, lib/qiita/markdown/version.rb
release
- https://github.com/increments/qiita-markdown/pull/141
=> Release v1.0.2

CHANGELOG.md, lib/qiita/markdown/version.rb
release
- https://github.com/increments/qiita-markdown/pull/134
- https://github.com/increments/qiita-markdown/pull/143
=> Release v1.0.3

CHANGELOG.md, lib/qiita/markdown/version.rb
Release
- https://github.com/increments/qiita-markdown/pull/146
=> Release v1.0.4

CHANGELOG.md, lib/qiita/markdown/version.rb
Release v1.1.0
- https://github.com/increments/qiita-markdown/pull/154
- https://github.com/increments/qiita-markdown/pull/151
- https://github.com/increments/qiita-markdown/pull/152
=> Release v1.1.0

CHANGELOG.md, lib/qiita/markdown/version.rb
Release v1.1.1
- https://github.com/increments/qiita-markdown/pull/149
- https://github.com/increments/qiita-markdown/pull/155
=> Release v1.1.1

CHANGELOG.md, lib/qiita/markdown/version.rb
Release v1.1.2
- https://github.com/increments/qiita-markdown/pull/157
- https://github.com/increments/qiita-markdown/pull/150
=> Release v1.1.2

CHANGELOG.md, lib/qiita/markdown/version.rb
Release v1.2.0
- https://github.com/increments/qiita-markdown/pull/159
=> Release v1.2.0

CHANGELOG.md, lib/qiita/markdown/version.rb
Release v1.4.0
- https://github.com/increments/qiita-markdown/pull/182
=> Release v1.4.0
