- CHANGELOG.md
- lib/qiita/markdown/filters/footnote.rb
- spec/qiita/markdown/processor_spec.rb
Previously, rendering the following markdown:
<sup><a href="#foo.1">Link</a></sup>
raised the following error:
Nokogiri::CSS::SyntaxError:
unexpected '.1' after '[#<Nokogiri::CSS::Node:0x007fe22c1481b8 @type=:CONDITIONAL_SELECTOR, @value=[#<Nokogiri::CSS::Node:0x007fe22c148258 @type=:ELEMENT_NAME, @value=["*"]>, #<Nokogiri::CSS::Node:0x007fe22c148ac8 @type=:ID, @value=["#foo"]>]>]'
> Fix error on rendering <a> tag with strange href inside of <sup> tag

- benchmark/heading_anchor_rendering.rb
- lib/qiita/markdown/greenmat/heading_rendering.rb
- lib/qiita/markdown/greenmat/html_renderer.rb
- lib/qiita/markdown/greenmat/html_toc_renderer.rb
- spec/qiita/markdown/greenmat/html_renderer_spec.rb
- spec/qiita/markdown/greenmat/html_toc_renderer_spec.rb
This fixes backward incompatibility of heading fragment identifiers that include special HTML characters in v0.5.0. For example, with Markdown document `# <b>R&amp;B</b>`, originally the fragment identifier for the heading was `#rb`. However in v0.5.0 it became `#brampb` unintentionally.
This change decreases the rendering performance a bit, but it's still faster than the previous post-process implementation.
> Fix backward incompatibility of heading fragment identifiers in v0.5.0

- lib/qiita/markdown.rb
- lib/qiita/markdown/greenmat/heading_rendering.rb
- lib/qiita/markdown/greenmat/html_toc_renderer.rb
- spec/qiita/markdown/greenmat/html_toc_renderer_spec.rb
This API is same as [`Redcarpet::Render::HTML_TOC`'s one](https://github.com/vmg/redcarpet/commit/3d71044c640383d91a190ed035223f4631c2b8b7), which is not yet released and will be released in Redcarpet 3.3.
> Add :escape_html extension to Greenmat::HTMLToCRenderer

- lib/qiita/markdown/processor.rb
- lib/qiita/markdown/summary_processor.rb
If you push custom filters into `Qiita::Markdown::Processor` instance many times, another instance variables can refer the other one, and continuing to increase.
So it should have been used `dup` or `clone` method.
> fix filters configurations.

- lib/qiita/markdown/filters/mention.rb
- qiita-markdown.gemspec
`HTML::Pipeline::MentionFilter#mention_link_filter` takes four arguments by v2. This commit simply ignores the new one because it seems we don't need that.
https://github.com/brittballard/html-pipeline/commit/57f6cce37cd2e7f941a3b8371b9f6e7597512347
review plz @r7kamura
> html-pipeline v2

- .rubocop.yml
- lib/qiita/markdown/filters/code.rb
- spec/qiita/markdown/processor_spec.rb
review plz @yujinakayama 
qiita-markdown uses liguist gem to detect code block languages from embedded file names,
and it returns `[Hack, PHP]` for files with ".php" extension. 
Linguist::Language.find_by_filename('hoge.php')
#=> [#<Linguist::Language name=Hack>, #<Linguist::Language name=PHP>]
Because qiita-markdown uses the first element as their language, this means that such code
blocks are detected as written in Hack language.
This commit let qiita-mardown treat "hack" as an alias for "php". By this, we can
highlight code blocks with not only such file name:
```hoge.php
class SampleClass {
public function hello() {
return "world";
}
}
```
but also "hack" as its language:
```hack:hoge.php
class SampleClass {
public function hello() {
return "world";
}
}
```
with PHP syntax …
> Treat "hack" as an alias for "php"

- CHANGELOG.md
- lib/qiita/markdown/filters/syntax_highlight.rb
- spec/qiita/markdown/processor_spec.rb
By default pygments' lexer automatically strips leading/trailing newlines in code snippets, but we want to leave them as they are.
https://github.com/tmm1/pygments.rb/blob/v0.6.3/vendor/pygments-main/pygments/lexer.py#L51-L52
> Avoid stripping leading and trailing newlines in code snippets

- .gitignore
- lib/qiita/markdown/filters/code.rb
- spec/qiita/markdown/processor_spec.rb
- spec/spec_helper.rb
As the HTML specification describes:
> Note: In the HTML syntax, a leading newline character immediately following the pre element start tag is stripped.
http://dev.w3.org/html5/spec-preview/the-pre-element.html
... we need to add a leading newline to the content of `<pre>` element so that the original leading newlines inputted by user are properly rendered on browsers.
> Add leading newline to <pre> element

- qiita-markdown.gemspec
Ruby versions which are less than 2.3 are NOT supported by the new activesupport version (5 series). Thus, currently, the build result by Travis CI was "failed" on the target Ruby versions. To fix this issue, fix the activesupport version.
> Fix the activesupport version to support  Ruby versions (less than 2.3)

- .rubocop.yml
- .rubocop_todo.yml
- lib/qiita/markdown/filters/mention.rb
- lib/qiita/markdown/filters/sanitize.rb
- spec/qiita/markdown/processor_spec.rb
- spec/qiita/markdown/summary_processor_spec.rb
This PR adds `class="js-user-hover-card"` and `data-user-url-name` attributes to `A` elements generated by the mention filter to implement user hover card feature in Qiita core.
@r7kamura, could you review this PR?
> Add some attributes to a elements for hover card

- CHANGELOG.md
- lib/qiita/markdown/filters/external_link.rb
- spec/qiita/markdown/processor_spec.rb
When we added the rel="nofollow" and target="_blank" to the external links, some experts were wondering whether we would also think about adding rel="noopener" as well.
http://b.hatena.ne.jp/entry/blog.qiita.com/post/149486954709/externallinkattrib
rel="noopener" is described in the following blogs.
- https://mathiasbynens.github.io/rel-noopener/
- https://blog.jxck.io/entries/2016-06-12/noopener.html
- https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/
In short, it prevents users from being affected with some security attack.
> Add rel="noopener" to external links

- README.md
seems gem badge markdown is broken. 
ref. https://badge.fury.io/for/rb/qiita-markdown
> Fix wrong markdown text for gem badge

- lib/qiita/markdown/filters/code.rb
- qiita-markdown.gemspec
- spec/qiita/markdown/processor_spec.rb
We have added leading newline handling in #27 but it seems that the latest pygments (which is bundled with pygments.rb 1.0 or later) automatically prepends empty `<span></span>` element to preserve leading newlines. So our handling is now redundant.
> Pygments.rb 1.0

- .travis.yml
- CHANGELOG.md
- qiita-markdown.gemspec
Since they are no longer maintained by the Ruby core team.
> Drop 2.0 and 2.1 from support Ruby versions

- lib/qiita/markdown/filters/user_input_sanitizer.rb
- spec/qiita/markdown/processor_spec.rb
TSIA
Qiita had allowed users to embed tweets unofficially. Now we decided to support it officially.
Twitter widgets.js only depends on `blockquote.twitter-tweet > a[href]`. Any other attributes and inner text are not important.
> ![image](https://user-images.githubusercontent.com/96157/27275979-8c352eea-5514-11e7-81e7-7d6893ef2bc8.png)
> Allow <blockquote class="twitter-tweet">

- CHANGELOG.md
- lib/qiita/markdown/greenmat/html_toc_renderer.rb
- spec/qiita/markdown/greenmat/html_toc_renderer_spec.rb
When converting the following markdown to html,
```markdown
```
`<a>` tag gets nested when using HTMLToCRenderer.
```html
<ul>
<li>
<a href="#hoge"><a href="#">hoge</a></a>
</li>
</ul>
```
- ~Strip `<ol>`, `<ul>`, `<li>`, `<a>` tags in HTMLToCRenderer~ -> Strip all html tags in HTMLToCRenderer when option of `:escape_html ` is true.
In the case of the above example, it becomes
```html
<ul>
<li>
<a href="#hoge">hoge</a>
</li>
</ul>
```
- Add some tests about it.
> Strip and escape HTML tags in ToC

- lib/qiita/markdown.rb
- lib/qiita/markdown/embed/asciinema.rb
- lib/qiita/markdown/filters/user_input_sanitizer.rb
- lib/qiita/markdown/transformers/filter_script.rb
- spec/qiita/markdown/processor_spec.rb
For enabling to embed asciinema script in Qiita main body, I fixed to allow loading `https://asciinema.org/a/xxxx.js` by script filter
> Allow Asciinema script

- lib/qiita/markdown/embed/code_pen.rb
Closes https://github.com/increments/qiita-markdown/issues/70
- Add new codepen embeded script url
- new url: https://cpwebassets.codepen.io/assets/embed/ei.js
https://qiita.com/genbu-jp/questions/634956ea77ade61af6c3
> Add new codepen embeded script url

- lib/qiita/markdown/transformers/filter_iframe.rb
- spec/qiita/markdown/processor_spec.rb
- allow relative url in iframe src attribute
- Slideshare uses relative urls in their templates
> Allow relative url in iframe

- lib/qiita/markdown.rb
- lib/qiita/markdown/filters/syntax_highlight.rb
- qiita-markdown.gemspec
- spec/qiita/markdown/processor_spec.rb
closes https://github.com/increments/qiita-markdown/issues/78
We stoped to use pygments in Qiita and Qiita Team, so change default syntax highlighter to rouge.
> Change syntax highlighter from pygments to rouge

- lib/qiita/markdown/filters/custom_block.rb
- spec/qiita/markdown/processor_spec.rb
- Fixed an error when custom block type is empty.
- example
```
:::
Some messages
:::
```
- Parse to simple div element if type is empty.
> Fix bug when type of custom block is empty

- lib/qiita/markdown/filters/group_mention.rb
I fix regular expressions to detect group id(url_name) for group mention.
Max length group id changed form 16 to 64(please check ref).
https://teams.qiita.com/guide/expand-group-char-limit/
> Fix group url length

- lib/qiita/markdown/filters/code_block.rb
- spec/qiita/markdown/processor_spec.rb
I fixed to support file names containing colons.
For example, 
~~~markdown
```ruby:test:example.rb
hoge
```
~~~
> Fix code metadata to allow containing colon

- CHANGELOG.md
- lib/qiita/markdown/version.rb
- [#113](https://github.com/increments/qiita-markdown/pull/113): Dropped Ruby 2.5 support by @mziyut
- [#114](https://github.com/increments/qiita-markdown/pull/114): Bump greenmat from 3.5.1.2 to 3.5.1.3 by @mziyut
> Release v0.41.0

- CHANGELOG.md
- lib/qiita/markdown/version.rb
- Add for Ruby3.x support by @maedana in https://github.com/increments/qiita-markdown/pull/116
- Bump greenmat from 3.5.1.3 to 3.5.1.4 by @mziyut in (https://github.com/increments/qiita-markdown/pull/117
> Release v0.42.0

- .github/workflows/test.yml
- CHANGELOG.md
Closee https://github.com/increments/qiita-markdown/issues/118
- Fix GitHub Actions can't be executed when public fork
- The CC_TEST_REPORTER_ID defined in secret cannot be obtained when forked, so the job of codeclimate is not executed when forked.
> Fix GitHub Actions can't be executed when public fork

- CHANGELOG.md
- lib/qiita/markdown/filters/checkbox.rb
- spec/qiita/markdown/filters/checkbox_spec.rb
I fixed bug of checkbox filter.
When checkbox mark (`- [ ]`) is followed by many spaces,
```
```
in GitHub, spaces are removed as follows.
However, Qiita Markdown's checkbox filter does not remove. So I added `lstrip` to remove spaces.
> Fix bug of checkbox filter when space exists after checkbox mark

- CHANGELOG.md
- README.md
Rename package name from `Qiita::Markdown` to `Qiita Markdown` in README
> Rename pagkage name

- CHANGELOG.md
- lib/qiita/markdown/version.rb
- #131 will be major version up and this version will be stable version of the version 0 series.
- https://github.com/increments/qiita-markdown/pull/128
- https://github.com/increments/qiita-markdown/pull/129
> Release v0.44.1

- .github/workflows/test.yml
- CHANGELOG.md
- qiita-markdown.gemspec
- Drop ruby 2.6 support
- ruby 2.6 is already EOL
- https://www.ruby-lang.org/en/downloads/branches/
> Drop Ruby 2.6 support

- CHANGELOG.md
- lib/qiita/markdown/version.rb
> **Warning**
> See [#130](https://github.com/increments/qiita-markdown/issues/130) for the breaking changes on some Markdown notations
- https://github.com/increments/qiita-markdown/pull/131
- https://github.com/increments/qiita-markdown/pull/135
> Release v1.0.0

- CHANGELOG.md
- lib/qiita/markdown/transformers/filter_attributes.rb
- Avoid sanitizing attributes related to footnotes
- To fix a bug that links to footnotes were disabled
> Allow attributes related to footnotes

- CHANGELOG.md
- qiita-markdown.gemspec
Closes https://github.com/increments/qiita-markdown/issues/133
- Bump rake version to work with ruby 3.2
- There was a problem in previous version of rake that did not work due to braking changes in Ruby 3.2
> Bump rake version to work with ruby 3.2

- CHANGELOG.md
- qiita-markdown.gemspec
Update rouge dependency.
Mainly breaking change is stop to support solidly lexer.
https://github.com/rouge-ruby/rouge/releases
https://github.com/rouge-ruby/rouge/compare/v3.26.0...v4.1.0
https://github.com/rouge-ruby/rouge/blob/master/CHANGELOG.md
> Bump rouge from 3.26.0 to 4.1.0

- .github/workflows/test.yml
- CHANGELOG.md
- qiita-markdown.gemspec
- Drop Ruby 2.7 support
- ruby 2.7 is already EOL
- qiita_marker-0.23.9 required Ruby >= 3.0
- Bump qiita_marker 0.23.6 to 0.23.9
- https://github.com/increments/qiita_marker/pull/40
- Drop Ubuntu 18.04 support
- Ubuntu 18.04 is already EOL
- Drop Ubuntu 18.04 support
- Because GitHub Actions fail jobs using Ubuntu 18.04
- https://github.com/increments/qiita-markdown/actions/runs/4988480359/jobs/9089846191
- https://github.com/actions/runner-images/issues/6002
- https://www.ruby-lang.org/en/downloads/branches/
> Bump qiita marker 0.23.6 to 0.23.9

- CHANGELOG.md
- Gemfile
- qiita-markdown.gemspec
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
`base64` is no longer be part of Ruby 3.4.0.
This PR is for adopting this update.
https://github.com/increments/qiita-markdown/actions/runs/7690101297/job/20953534987?pr=151
> /home/runner/work/qiita-markdown/qiita-markdown/vendor/bundle/ruby/3.4.0+0/gems/rubocop-1.39.0/lib/rubocop/formatter/html_formatter.rb:6: warning: base64 was loaded from the standard library, but is not part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
> Update rubocop for Ruby 3.4

- CHANGELOG.md
- qiita-markdown.gemspec
Update rouge dependency.
CHANGELOG
https://github.com/rouge-ruby/rouge/blob/master/CHANGELOG.md#version-420-2023-10-25
There is no breaking change.
> Update rouge dependency version to '~> 4.2'

- CHANGELOG.md
- lib/qiita/markdown.rb
Ruby 3.4 does not support `uri` modules by default.
This PR is for adopting this update.
https://github.com/increments/qiita-markdown/actions/runs/7704576731/job/20997185179?pr=153
```
```
> Add uri to require list for ruby 3.4

- lib/qiita/markdown/filters/final_sanitizer.rb
- lib/qiita/markdown/filters/user_input_sanitizer.rb
- spec/qiita/markdown/processor_spec.rb
- allow `open` attribute in `details` element
> Allow open attribute on details

- lib/qiita/markdown/filters/code_block.rb
- qiita-markdown.gemspec
I have trouble to install 1.6.x of rugged. The following error has occurred.
```
Installing rugged 1.6.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.                                                     
current directory: /home/maedana/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rugged-1.6.3/ext/rugged            
/home/maedana/.rbenv/versions/3.2.2/bin/ruby extconf.rb --use-system-libraries                                         
checking for gmake... no                                                                                               
checking for make... yes                                                                                               
Building Rugged using system libraries. …
```
> Upgrade github-linguist from 4.x to 7.x

- spec/qiita/markdown/filters/code_block_spec.rb
- add test for code_block filter
> Add test for code_block filter

- lib/qiita/markdown/embed/code_pen.rb
- spec/qiita/markdown/processor_spec.rb
- Add new codepen embeded script url
- new url: https://public.codepenassets.com/embed/index.js
- Refactor codepen embed code tests
- https://github.com/increments/qiita-discussions/discussions/956
> Add new codepen embed script url public.codepenassets.com

- .github/workflows/test.yml
Close https://github.com/increments/qiita-markdown/issues/145
- Bump Ruby version on ci
- https://www.ruby-lang.org/en/downloads/branches/
> Bump Ruby version on ci

- .github/workflows/release.yml
- Add GitHub Actions workflow for releasing gem to RubyGems.org
- Use https://github.com/rubygems/release-gem
- We always execute the release command locally
- https://github.com/increments/graphql-kaminari_connection/pull/36
- Already setup RubyGems Trusted Publishing
- https://github.com/increments/qiita-dev/issues/7383#issuecomment-2975145721
- Already setup `release` environment
- https://github.com/increments/qiita-dev/issues/7383#issuecomment-2975362104
> Add workflow for releasing gem

- CHANGELOG.md
- lib/qiita/markdown/version.rb
Release v1.3.0
- https://github.com/increments/qiita-markdown/pull/163
- https://github.com/increments/qiita-markdown/pull/176
> Release v1.3.0

- .github/workflows/test.yml
- Gemfile
- README.md
- spec/spec_helper.rb
- Remove use codeclimate
- Remove codeclimate badge from README
- Stop use and uninstall codeclimate-test-reporter gem
- Remove codeclimate CI
- Code Climate API was disabled
- https://docs.qlty.sh/migration/guide
> Remove codeclimate

- lib/qiita/markdown/embed/figma.rb
- lib/qiita/markdown/transformers/filter_iframe.rb
- spec/qiita/markdown/processor_spec.rb
- Add new figma embeded script url
- new url: https://www.figma.com/developers/embed#overview
- Refactor figma embed code tests
> Add new figma embed script host embed.figma.com
